=== Ttibsi/msc_cs_ai/COM00142M_Advanced_Programming/exercises/w2.4_definition.dtd
<!ELEMENT test_results (students)>
<!ELEMENT students (student+)>
<!ELEMENT student (result+)>
    <!ATTLIST student id #CDATA>
    <!ATTLIST student name #CDATA>
<!ELEMENT result (int)>
    <!ATTLIST result class #CDATA>
    <!ATTLIST result type #CDATA>

=== Ttibsi/msc_cs_ai/COM00142M_Advanced_Programming/exercises/w2.4_xml.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE library SYSTEM "w2.4_definition.dtd">
<test_results>
    <students>
        <student id="16430122-1521" name="Page, Camden G.">
            <result class="mathmatics" type="test 1">54</result>
            <result class="mathmatics" type="test 2">63</result>
        </student>
        <student id="16470212-9851" name="Weber, Lucy X">
            <result class="mathmatics" type="test 1">32</result>
            <result class="mathmatics" type="test 2">41</result>
        </student>
    </students>
</test_results>
